spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Ragman226#
    url: jdbc:mysql://localhost:3306/memberdb
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
